export const configFields = [
  {
    hotels: [
      {
        name: "Pullman Orchard Stage",
        hotelId: "989814e5-2fda-4ab8-b795-33f4d76f1866",
        details: [],
      },
      {
        name: "Sofitel Manila",
        hotelId: "259034ee-3f5c-43b0-9332-dffd85ccba65",
        details: [],
      },
      {
        name: "Londoner Leicester Square",
        hotelId: "aa211eb9-110c-47cb-ade4-7db0e6da20b4",
        details: [],
      },
    ],
    modules: [
      {
        name: "Home",
        details: [],
      },
      {
        name: "FaceScan",
        details: [],
      },
      {
        name: "BookingID",
        details: [],
      },
      {
        name: "ConfirmationID",
        details: [],
      },
      {
        name: "CheckoutKey",
        details: [],
      },
      {
        name: "ScanDoc",
        details: [],
      },
      {
        name: "KeyCard",
        details: [],
      },
    ],
    submodules: [
      {
        name: "accompanyingGuest",
        details: [],
      },
      {
        name: "cardPreAuthorize",
        details: [],
      },
      {
        name: "cardAuthorize",
        details: [],
      },
      {
        name: "checkIn",
        details: [
          {
            title: "ENHANCE YOUR STAY! SHARE YOUR DESIRES BELOW",
          },
          {
            name: "firstName",
            label: "First Name",
            type: "Text",
            required: true,
            isDisabled: true,
            isActive: true,
          },
          {
            name: "lastName",
            label: "Last Name",
            type: "Text",
            required: true,
            isDisabled: true,
            isActive: true,
          },
          {
            name: "emails",
            label: "Email",
            type: "Text",
            required: true,
            isDisabled: false,
            isActive: true,
          },
          {
            name: "phone",
            label: "Phone Number",
            type: "tel",
            required: true,
            isDisabled: false,
            isActive: true,
          },
          {
            name: "docType",
            label: "Document Type",
            type: "AutoComplete",
            required: true,
            isDisabled: false,
            isActive: true,
          },
          {
            name: "docNo",
            label: "Document Number",
            type: "Text",
            required: true,
            isDisabled: false,
            isActive: true,
          },
          {
            name: "condition",
            label:
              "I agree to receive an invitation email to validate and sign up for a complimentary ACCOR Membership.",
            type: "CheckBox",
            required: true,
            isDisabled: false,
            isActive: false,
          },
        ],
      },
      {
        name: "signStayInfo",
        details: [],
      },
    ],
    Keys: [
      {
        code: [
          "pullman-orchard-stage",
          "home",
          "faceScan",
          "bookingId",
          "stayDetails",
          "checkoutKey",
          "scanDoc",
          "keyCard",
          "review",
          "activateOrComplete",
          "cardConformation",
          "rating",
          "emailPopup",
          "checkOut",
          "banner",
          "terms",
        ],
        pms: ["OPERA", "INFOR"],
        fetchFromDb: ["yes", "no"],
        saveToDb: ["yes", "no"],
        name: [
          "Pullman Singapore Orchard Stage",
          "Identity Verification",
          "Card Confirmation",
          "Card Authorization",
          "Review & Sign",
          "Check-in",
          "Stay Information",
          "Guest Information",
          "Credit Card Information",
          "Finish your Check-in",
        ],
        description: [
          "Kindly use your card for payment",
          "Confirm your email ID ",
        ],
        description1: [
          "Key Card Activated",
          "You've Checked-out",
          "How was your stay?",
        ],
        description2: ["Check-in Completed", "How was your stay?"],
        label: [
          "Booking ID",
          "Room Number (In 4 Digits)",
          "Accompanying Guest",
          "First Name",
          "Last Name",
          "Document Number",
          "Email",
          "Payment Successful",
          "Add your e-signature",
        ],
        title: [
          "Place Your Key",
          "Jingle, Shop & Stay",
          "Card Confirmation",
          "Email Invoice",
          "PREAMBLE",
        ],
        details: [],
      },
    ],
  },
];
